name: Security-pipeline include
on:
  workflow_call:
  pull_request:

jobs:
  code-scan:
    runs-on: self-hosted
    permissions:
      pull-requests: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: code-scan
      env:
          SEC_RULES_TOKEN: ${{ secrets.SEC_RULES_TOKEN }}
          CI_COMMIT_REF_NAME: ${{ github.head_ref || github.ref_name }}
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          export CI_COMMIT_REF_NAME="${CI_COMMIT_REF_NAME}"
          docker run --rm -v ${{ github.workspace }}:/project \
          -e GITHUB_ACTIONS="true" \
          -e CI_COMMIT_AUTHOR="${{ github.actor }}" \
          -e CI_JOB_ID="${{ github.run_id }}-${{ github.run_number }}" \
          -e CI_COMMIT_SHA="${{ github.sha }}" \
          -e CI_PROJECT_ID="${{ github.repository_id }}" \
          -e CI_GROUP_ID="0" \
          -e CI_PROJECT_NAME="${{ github.event.repository.name }}" \
          -e CI_PROJECT_NAMESPACE="${{ github.repository_owner }}" \
          -e CI_PROJECT_PATH="${{ github.repository }}" \
          -e CI_PIPELINE_ID="${{ github.run_id }}" \
          -e CI_PROJECT_DIR='/project' \
          -e CI_JOB_TOKEN="${{ secrets.SEC_RULES_TOKEN }}" \
          -e CI_SERVER_HOST="${{ github.server_url }}" \
          -e CI_COMMIT_REF_NAME="${CI_COMMIT_REF_NAME}" \
          -e CI_PROJECT_URL="${{ github.server_url }}/${{ github.repository }}" \
          -e CI_PIPELINE_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
          -e DANGER_GITLAB_API_TOKEN=${{ secrets.GITHUB_TOKEN }} \
          -e CI_MERGE_REQUEST_SOURCE_BRANCH_NAME=${{ github.head_ref }} \
          -e CI_MERGE_REQUEST_TARGET_BRANCH_NAME=${{ github.base_ref }} \
          -e CI_MERGE_REQUEST_DIFF_BASE_SHA=${{ github.event.pull_request.base.sha }} \
          -e CI_MERGE_REQUEST_IID=${{ github.event.pull_request.number }} \
          -e CI_MERGE_REQUEST_PROJECT_URL=${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.pull_request.number }} \
          -e CI_MERGE_REQUEST_SOURCE_PROJECT_URL=${{ github.event.pull_request.head.repo.html_url }} \
          -e CI_MERGE_REQUEST_SOURCE_BRANCH_SHA=${{ github.event.pull_request.head.sha }} \
          security-pipelines:0.1
