name: Security-pipeline include
on:
  workflow_call:
jobs:
  code-scan:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 
    - name: code-scan
      run: |
          docker run --rm -v ${{ github.workspace }}:/project \
          -e CI_JOB_ID="${{ github.run_id }}-${{ github.run_number }}" \
          -e CI_COMMIT_SHA="${{ github.sha }}" \
          -e CI_PROJECT_ID="${{ github.repository_id }}" \
          -e CI_PROJECT_NAME="${{ github.event.repository.name }}" \
          -e CI_PROJECT_NAMESPACE="${{ github.repository_owner }}" \
          -e CI_PROJECT_PATH="${{ github.repository }}" \
          -e CI_PIPELINE_ID="${{ github.run_id }}" \
          -e CI_PROJECT_DIR='/project' \
          -e CI_JOB_TOKEN="${{ secrets.SEC_RULES_TOKEN }}" \
          -e CI_SERVER_HOST="${{ github.server_url }}" \
          -e CI_COMMIT_REF_NAME="${{ github.ref_name }}" \
          -e CI_PROJECT_URL="${{ github.server_url }}/${{ github.repository }}" \
          -e CI_PIPELINE_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
          -e DANGER_GITLAB_API_TOKEN='TOKENN' \
          hub.softswiss.net/security-pub/pipeguard:feature-nl-appsec-541-github
